alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../main.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../tx_pll.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../ram.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../tx.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../rx.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../o_counter.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../vga_control.v"
alog -O2 -protect 0 -msg 5 -sve "$dsn/../../../tx_pll_fast.v"
